DB_PASS: "hunas"
GROUP_TOKEN: "vk1.a.BwzhpjkWPeWTC0mq-8QfU5jrldMLXpZGGT1BVqyLQsnmtqbuexlYlG9rUrhZQy1gZb7abI6eQ8i4zvlG4xZwJ0d8o1SjS7tdK6YredgoGVL9uOq8ZJW0yNyROMje_zynfG7FY-KahOhnC-KrSygld_blZ4CXCyJdSMtlsdGePE7WoVIzx9c-TmKSfhmcWaHZAZTc0ShcKWsRzljZj7FMqw"
ACCESS_TOKEN: "vk1.a.yE0FHUPMrj-h6hAM13_yUpde94amRszUpraBvIXwmjus3xmNXjnale1XrBs4Dcy8dD5wPFGBaShdWEf0mPPqvNKVV4bhnP5LtOje7FODy7BhRr0zPBzPCT3e6wKafnSt3cY5pTB8Wmc0Ol9GEv6tPzrXAlIbzL_lfqN5Kgt4vN6pZFnyW6lwRZoxjnyB1BQalrtzb1vDoenVS_U0miX3NA"

